---

  - hosts: all
    become: true
    tasks:

    - name: apt-update calistirir
      apt:
        update_cache: yes
        #cache_valid_time: 86400

    - name: apache2 paketini kaldirir.
      apt:
        name: apache2
        state: absent

    - name: apache2 icin php kutuphanesini kaldirir.
      apt:
        name: libapache2-mod-php
        state: absent