---

  - hosts: ubuntu
    become: true
    tasks:

    - name: apache2 paketini kaldirir
      ansible.builtin.apt:
        name: apache2
        state: absent
    
    - name: apache2 icin php kutuphanesini kaldirir.
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: absent

    